## 🧮 Module 5: Working with Numpy Arrays & Simple APIs

---

In this module, we will explore the basics of communication between web applications using the HTTP protocol and the use of Python APIs. You will learn how requests and responses work on the web, how to interact with public APIs and how to process data in different formats. In addition, we will address key concepts such as the difference between APIs and REST APIs, and perform basic web scraping tasks to extract information from websites.


## 🎯 Objectives

In this module, you will learn how to:

- Understand the use of the **HTTP protocol** using the `requests` library
- Describe how **URL request and response** workflows operate in HTTP
- Apply simple and public **APIs** using Python
- Perform basic web scraping
- Work with different **file formats** (CSV, JSON, etc.)
- Explain the **difference between APIs and REST APIs**.
- Summarize how APIs **receive and send information**.
---

## 🔢 Working with NumPy Arrays

### ✅ 1D Arrays

**Creating and using NumPy 1D arrays:**

In [1]:
import numpy as np

a = np.array([0, 1, 2])
b = np.array([2, 1, 0])
result = a * b  # Element-wise multiplication
print(result)   # Output: [0 1 0]

[0 1 0]


**Dot product example:**

In [2]:
# Example of dot product
np.dot(np.array([1, 2]), np.array([3, 4]))  # 1*3 + 2*4 = 11

np.int64(11)

---

### ✅ 2D Arrays

**Creating and accessing NumPy 2D arrays:**

In [3]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A.shape)  # (3, 2) → 3 rows, 2 columns

(3, 2)


**Matrix multiplication:**

In [4]:
B = np.array([[1, 2, 3], [4, 5, 6]])
C = np.dot(A, B)
print(C)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


---

## 🌐 Simple APIs with Python

### 🔹 HTTP Requests

Using the `requests` library to make HTTP calls:

In [5]:
import requests

response = requests.get("https://api.github.com")
print(response.status_code)  # 200 if successful
print(response.json())       # Display returned JSON data

200
{'current_user_url': 'https://api.github.com/user', 'current_user_authorizations_html_url': 'https://github.com/settings/connections/applications{/client_id}', 'authorizations_url': 'https://api.github.com/authorizations', 'code_search_url': 'https://api.github.com/search/code?q={query}{&page,per_page,sort,order}', 'commit_search_url': 'https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}', 'emails_url': 'https://api.github.com/user/emails', 'emojis_url': 'https://api.github.com/emojis', 'events_url': 'https://api.github.com/events', 'feeds_url': 'https://api.github.com/feeds', 'followers_url': 'https://api.github.com/user/followers', 'following_url': 'https://api.github.com/user/following{/target}', 'gists_url': 'https://api.github.com/gists{/gist_id}', 'hub_url': 'https://api.github.com/hub', 'issue_search_url': 'https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}', 'issues_url': 'https://api.github.com/issues', 'keys_url': 'https://api

---

### 🔹 How HTTP Works

- A client sends a **request** to a URL (endpoint)  
- The server sends back a **response** (status code + data)  
- Data is often returned in **JSON** format  

---

## 📡 APIs vs REST APIs

| Feature   | API                        | REST API                        |
|-----------|----------------------------|----------------------------------|
| Protocol  | May use different protocols| Always uses HTTP                |
| Format    | Varies                     | Commonly JSON or XML            |
| Methods   | Function calls             | HTTP methods: GET, POST, PUT, DELETE |

---

## 🧪 Lab Examples

### 🔍 Example 1: Element-wise operations

In [6]:
a = np.array([0, 1, 0, 1, 0])
b = np.array([1, 0, 1, 0, 1])
print(a * b)  # Output: [0 0 0 0 0]

[0 0 0 0 0]


### 🔍 Example 2: Dot Product

In [7]:
a = np.array([0, 1])
b = np.array([1, 0])
print(np.dot(a, b))  # Output: 0

0


### 🔍 Example 3: Broadcasting

In [8]:
a = np.array([1, 1, 1, 1, 1])
print(a + 10)  # Output: [11 11 11 11 11]

[11 11 11 11 11]


### 🔍 Example 4: Valid Matrix Multiplication

In [9]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
C = np.dot(A, B)
print(C)  # Output: [[4 4], [10 8]]

[[ 4  4]
 [10  8]]


---

This content is based on the IBM Cognitive Class course Python 101 for Data Science, Module 3: Python Programming Fundamentals. Exercises and review questions reinforce understanding of core collection types in Python.



---